On cosmo:
When compiling testSimReadKcorr testsimulateIGM testSimulation, get the following
errors:

1)
/usr/bin/ld: /usr/local/Sophya//slb//libextsophya.so: undefined reference to symbol 'fftw_destroy_plan'
/usr/bin/ld: note: 'fftw_destroy_plan' is defined in DSO /usr/local/extLibs/lib/libfftw3.so so try adding it to the linker command line
/usr/local/extLibs/lib/libfftw3.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make: *** [/home/alex/Software/DirectSim/exe/testSimulation] Error 1

therefore commented these programs out from being automatically built on
typing 'make'

2)
SOPHYA library, BaseDataTable::GetMinMax doesn't seem to support the overloaded
method GetMinMax(string const &nom, double &min, double &max) const, where the
name (rather than the index) of column is given

so edited progs/colorDistributions.cc to correct this